const APP_VERSION='2.0.0';
const S={qs:[],game:null,screen:'home',reviewList:null,reviewIndex:0};
const $=s=>document.querySelector(s);
const shuffle=a=>{a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
const loadJSON=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}};
const save=()=>localStorage.setItem('csp_game',JSON.stringify(S.game));
const bookmarks=()=>new Set(loadJSON('csp_bookmarks',[]));
function esc(x){return String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function eligible(){return S.qs.filter(q=>!q.is_math && q.options?.length>=2 && Number.isInteger(q.correct_answer));}
function byDomain(d){return eligible().filter(q=>q.domain===d)}
function sample(arr,n){return shuffle(arr).slice(0,Math.min(n,arr.length))}
function samplePriority(pool,n){const sm=pool.filter(q=>q.source_type==='Study Material'),qb=pool.filter(q=>q.source_type==='Question Bank');const smNeed=Math.min(sm.length,Math.ceil(n*0.7));let out=sample(sm,smNeed);let left=n-out.length;out.push(...sample(qb.filter(q=>!out.includes(q)),left));left=n-out.length;if(left>0)out.push(...sample(pool.filter(q=>!out.includes(q)),left));return out.slice(0,n)}
function nextSplit(){let toggle=Number(localStorage.getItem('csp_d12_toggle')||0); localStorage.setItem('csp_d12_toggle',String(1-toggle)); return toggle===0?[13,12]:[12,13];}
function newGame(){const [d1,d2]=nextSplit();const need={1:d1,2:d2,3:5,4:5,5:5,6:5,7:5};let picked=[];for(const d of [1,2,3,4,5,6,7]){const pool=byDomain(d);if(pool.length<need[d]){alert(`Not enough non-math questions in Domain ${d}.`);return}picked.push(...samplePriority(pool,need[d]))}picked=shuffle(picked);S.game={id:Date.now(),questions:picked.map(q=>q.question_id),index:0,answers:{},startedAt:Date.now(),finished:false,mode:'game',split:{1:d1,2:d2,3:5,4:5,5:5,6:5,7:5}};save();S.screen='game';render()}
function currentQ(){return S.qs.find(q=>q.question_id===S.game.questions[S.game.index])}
function answer(i){const q=currentQ();if(S.game.answers[q.question_id]!=null)return;S.game.answers[q.question_id]=i;save();render()}
function next(){if(S.game.index<S.game.questions.length-1){S.game.index++;save();render()}else{S.game.finished=true;save();S.screen='results';render()}}
function toggleBookmark(id){const b=bookmarks();b.has(id)?b.delete(id):b.add(id);localStorage.setItem('csp_bookmarks',JSON.stringify([...b]));render()}
function scoreData(){let c=0,w=0,dom={};for(const id of S.game.questions){const q=S.qs.find(x=>x.question_id===id);const a=S.game.answers[id];if(!dom[q.domain])dom[q.domain]={correct:0,total:0};if(a!=null){dom[q.domain].total++;if(a===q.correct_answer){c++;dom[q.domain].correct++}else w++}}const total=S.game.questions.length;return{c,w,dom,total,pct:total?Math.round(c/total*100):0}}
function reviewWrong(){const ids=S.game.questions.filter(id=>{const q=S.qs.find(x=>x.question_id===id);return S.game.answers[id]!=null&&S.game.answers[id]!==q.correct_answer});S.reviewList=ids;S.reviewIndex=0;S.screen='review';render()}
function practiceDomain(d){let pool=shuffle(byDomain(d));S.game={id:Date.now(),questions:pool.map(q=>q.question_id),index:0,answers:{},startedAt:Date.now(),finished:false,mode:'domain',domain:d};save();S.screen='game';render()}
function practiceBookmarks(){const b=bookmarks();const pool=shuffle(eligible().filter(q=>b.has(q.question_id)));if(!pool.length){alert('No bookmarked questions yet.');return}S.game={id:Date.now(),questions:pool.map(q=>q.question_id),index:0,answers:{},startedAt:Date.now(),finished:false,mode:'bookmarks'};save();S.screen='game';render()}
function practiceWrong(){const hist=loadJSON('csp_wrong_history',[]);const ids=[...new Set(hist)].filter(id=>S.qs.some(q=>q.question_id===id&&!q.is_math));if(!ids.length){alert('No saved wrong answers yet.');return}S.game={id:Date.now(),questions:shuffle(ids),index:0,answers:{},startedAt:Date.now(),finished:false,mode:'wrong'};save();S.screen='game';render()}
function finishStore(){if(!S.game?.finished)return;let h=loadJSON('csp_wrong_history',[]);for(const id of S.game.questions){const q=S.qs.find(x=>x.question_id===id);if(S.game.answers[id]!=null&&S.game.answers[id]!==q.correct_answer)h.push(id)}localStorage.setItem('csp_wrong_history',JSON.stringify(h.slice(-1000)))}
function home(){const resumable=S.game&&!S.game.finished&&S.game.questions?.length;const counts={};for(let d=1;d<=7;d++)counts[d]=byDomain(d).length;$('#app').innerHTML=`<div class="wrap home"><div class="top"><div class="brand">CSP Revision Game</div><span class="pill">Offline PWA</span></div><h1>Fast CSP Revision</h1><p class="muted">50-question games. Study Material priority. No calculation questions in normal game.</p><div class="card grid"><button class="primary" id="new">New Random Game</button>${resumable?'<button class="secondary" id="resume">Resume Unfinished Game</button>':''}<button class="secondary" id="wrong">Wrong Answers Only</button><button class="secondary" id="fav">Bookmarks / Favorites</button></div><div class="card"><b>Domain-wise Practice</b><div class="grid2" style="margin-top:12px">${[1,2,3,4,5,6,7].map(d=>`<button class="secondary dpractice" data-d="${d}">Domain ${d} <span class="muted small">(${counts[d]})</span></button>`).join('')}</div></div><div class="card small muted">Normal game distribution alternates Domain 1/2 as 13+12, then 12+13. Domains 3–7 use 5 each. Study Material is prioritized (~70% of each domain selection), then Question Bank. Source wording and explanations are stored separately from the interface.</div></div>`;$('#new').onclick=newGame;if(resumable)$('#resume').onclick=()=>{S.screen='game';render()};$('#wrong').onclick=practiceWrong;$('#fav').onclick=practiceBookmarks;document.querySelectorAll('.dpractice').forEach(b=>b.onclick=()=>practiceDomain(Number(b.dataset.d)))}
function game(){const q=currentQ();const idx=S.game.index;const ans=S.game.answers[q.question_id];const done=ans!=null;const b=bookmarks().has(q.question_id);const total=S.game.questions.length;const progress=((idx+(done?1:0))/total)*100;$('#app').innerHTML=`<div class="wrap"><div class="top"><button class="secondary" id="home">Home</button><button class="bookmark" id="bm" aria-label="bookmark">${b?'★':'☆'}</button></div><div class="card"><div class="qhead"><span>Question ${idx+1}/${total}</span><span>${S.game.mode==='game'?'Score '+Object.keys(S.game.answers).filter(id=>{let qq=S.qs.find(x=>x.question_id===id);return S.game.answers[id]===qq?.correct_answer}).length:''}</span></div><div class="progress"><div style="width:${progress}%"></div></div><div class="question">${esc(q.question)}</div><div class="options">${q.options.map((o,i)=>{let cls='opt';if(done){if(i===q.correct_answer)cls+=' correct';if(i===ans&&i!==q.correct_answer)cls+=' wrong';if(i===ans)cls+=' selected'}return `<button class="${cls}" data-i="${i}" ${done?'disabled':''}><b>${String.fromCharCode(65+i)}.</b> ${esc(o)}</button>`}).join('')}</div>${done?`<div class="feedback ${ans===q.correct_answer?'good':'bad'}">${ans===q.correct_answer?'Correct':'Incorrect'}</div><div class="explanation"><b>Source explanation</b><br>${esc(q.explanation)}</div><div class="meta">Domain ${q.domain} · ${esc(q.source_files.join(' + '))}${q.is_math?' · Calculation-tagged':''}</div><button class="primary" id="next">${idx===total-1?'Finish':'Next Question'}</button>`:''}</div></div>`;$('#home').onclick=()=>{S.screen='home';render()};$('#bm').onclick=()=>toggleBookmark(q.question_id);if(!done)document.querySelectorAll('.opt').forEach(x=>x.onclick=()=>answer(Number(x.dataset.i)));else $('#next').onclick=next}
function results(){finishStore();const s=scoreData();$('#app').innerHTML=`<div class="wrap"><div class="top"><div class="brand">Game Complete</div><button class="secondary" id="home">Home</button></div><div class="card"><div class="grid2"><div class="stat"><b>${s.c}/${s.total}</b><div class="muted">Correct</div></div><div class="stat"><b>${s.pct}%</b><div class="muted">Percentage</div></div><div class="stat"><b>${s.w}</b><div class="muted">Wrong</div></div><div class="stat"><b>${s.total-s.c-s.w}</b><div class="muted">Unanswered</div></div></div></div><div class="card"><b>Performance by Domain</b>${Object.entries(s.dom).map(([d,v])=>`<div class="domainrow"><span>Domain ${d}</span><b>${v.correct}/${v.total}</b></div>`).join('')}</div><button class="primary" id="review">Review Wrong Answers</button><button class="secondary" style="width:100%;margin-top:10px" id="new">New Random Game</button></div>`;$('#home').onclick=()=>{S.screen='home';render()};$('#review').onclick=reviewWrong;$('#new').onclick=newGame}
function review(){if(!S.reviewList?.length){$('#app').innerHTML=`<div class="wrap"><div class="card"><b>No wrong answers to review.</b><button class="primary" id="home">Home</button></div></div>`;$('#home').onclick=()=>{S.screen='home';render()};return}const id=S.reviewList[S.reviewIndex],q=S.qs.find(x=>x.question_id===id),ans=S.game.answers[id];$('#app').innerHTML=`<div class="wrap"><div class="top"><button class="secondary" id="back">Results</button><span>Wrong ${S.reviewIndex+1}/${S.reviewList.length}</span></div><div class="card"><div class="question">${esc(q.question)}</div><div class="options">${q.options.map((o,i)=>`<div class="opt ${i===q.correct_answer?'correct':''} ${i===ans&&i!==q.correct_answer?'wrong':''}"><b>${String.fromCharCode(65+i)}.</b> ${esc(o)}</div>`).join('')}</div><div class="explanation"><b>Source explanation</b><br>${esc(q.explanation)}</div><div class="meta">Domain ${q.domain} · ${esc(q.source_files.join(' + '))}</div>${S.reviewIndex<S.reviewList.length-1?'<button class="primary" id="rn">Next Wrong Answer</button>':'<button class="primary" id="back2">Back to Results</button>'}</div></div>`;$('#back').onclick=()=>{S.screen='results';render()};if($('#rn'))$('#rn').onclick=()=>{S.reviewIndex++;render()};if($('#back2'))$('#back2').onclick=()=>{S.screen='results';render()}}
function render(){if(S.screen==='home')home();else if(S.screen==='game')game();else if(S.screen==='results')results();else if(S.screen==='review')review()}
(async()=>{S.qs=await fetch('questions.json').then(r=>r.json());S.game=loadJSON('csp_game',null);if(S.game?.finished)S.screen='home';render();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{})})();
